#ifndef EXELERATOR_VERSION_H
#define EXELERATOR_VERSION_H

#define EXELERATOR_VERSION_MAJOR 0
#define EXELERATOR_VERSION_MINOR 1
#define EXELERATOR_VERSION_PATCH 0

#define EXELERATOR_VERSION "0.1.0"

#endif
